### PR TITLE
Build changes

### PR DESCRIPTION
**Pull request by mediocregopher**
This ended up not NEEDing any changes, but there was one main one I wanted to make so here it is. Instead of using `CCWEB_DEBUG` in the Makefile you can use the generic `CRYPTIC_DEBUG` which is already being set up with chef. It's `true` for vagrant boxes and `false` for everything else.

Other than that, minor changes

### CODE REVIEW

**Comment by MarcoPolo** [comment]
Does CRYPTIC_DEBUG change anything in ccapi? or anywhere else?

**Comment by mediocregopher** [comment]
It puts ccapi into debug yeah. But debug mode just means it outputs more logs.

**Comment by MarcoPolo** [comment]
So it should have the same behavior when it's on or off? I toggle it quite a bit.

**Comment by mediocregopher** [comment]
Right. I think the only behavioral change in ccapi is that it won't check multipass. Everything else should be the same

**Comment by MarcoPolo** [comment]
I'm leaning towards having separate debug variables. I use them for things like auto logging in (for working on user stuff), and I'd like to be able to do that with multipass on/off. I don't think it makes sense, at least for now, to have them linked.

**Comment by mediocregopher** [comment]
Ok that's fine. I figured it would be simpler for you to keep them all together.

**Comment by MarcoPolo** [comment]
Take out 8dd2df6 and I'll merge it in

**Comment by mediocregopher** [comment]
Ok took it out

**Pull request merged**
